FROM nvidia/cuda:12.6.2-devel-ubuntu22.04

# Prevent tzdata from prompting during install
ENV DEBIAN_FRONTEND=noninteractive

# Default workdir
WORKDIR /workspace

# Install prerequisites for adding PPA and building Python packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    build-essential git wget \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y --no-install-recommends \
    python3.11 python3.11-venv python3.11-dev python3.11-distutils \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Ensure "python" points to python3.11
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.11 2 \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
    && update-alternatives --config python

# Upgrade pip for Python 3.11
RUN python -m ensurepip \
    && python -m pip install --upgrade pip

# TODO: Add pip install for timesfm


# Copy current repository into the container
COPY . /workspace

CMD ["/bin/bash"]